### ISSUE TITLE
user and item feature processing part for Recsys2017

### ISSUE THREAD

**Issue by schopra6** [layer6ai-labs/DropoutNet#7]
Hi , Thanks for sharing the code along with paper for this interesting approach. Could you also please explain the preprocessing part for user,item content and user,item preference array(U.csv.bin,V.csv.bin). For preference vectors , is it  SVD used to get latent representations? For content vectors, it is mentioned that after cleaning and transforming all categorical inputs into 1-of-n representation they ended up with 831 user features and 2738 item features. 
What were the cleaning steps and how did you end up with 831 and 2738 features? Maybe if possible, please share the code.

**Comment by guangster** [comment]
Hi, thanks for your interest in our work.

We use WMF from Hu 2008 to obtain our pref vectors instead of SVD since it is better for implicit feedback but it is inspired by SVD (hu 2008).
We also found WMF to be better in terms of cold-start performance (ie table 1 in our paper).

For content, we just used the recsys features with categorical maps (1-of-n). I don't remember exactly the settings and I cannot find the code anymore. I remember the cleaning bit is just to remove the categories with very few users/items so the overall # of features doesn't blow up too big.

Hope that helps!
